name: lemon_widgets
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter

  image: ^4.0.17
  universal_html: ^2.0.8
  file_picker: ^5.3.3


