
enum EditorRequest {
   GameObject,
   Set_Node,
   Load_Scene,
   Download,
   Modify_Canvas_Size,
   Save,
   Spawn_AI,
   Clear_Spawned,
   Scene_Set_Floor_Type,
   Generate_Scene,
   Toggle_Game_Running,
   Scene_Reset,
   Mark_Add,
   Mark_Delete,
   Mark_Select,
   Mark_Set_Type,
   New_Scene,
   Add_Key,
   Delete_Key,
   Move_Key,
   Rename_Key,
   Set_Variation,
}