name: gamestream_flutter
description: next gen cloud gaming

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  archive: ^3.3.6
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.0.1
  just_audio: ^0.9.28
  universal_html: ^2.0.8
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  golden_ratio: 1.0.6
  http: ^0.13.4
  intl: ^0.17.0
  typedef: ^1.0.5
  url_launcher: ^6.1.10

  lemon_sprite:
    path: ..\lemon_sprite
  lemon_widgets:
    path: ..\lemon_widgets
  lemon_math:
    path: ..\dart-lemon-math
  lemon_byte:
    path: C:\Users\Jerome\github\dart-lemon-byte
  lemon_engine:
    path: ..\dart-lemon-engine
  firestore_client:
    path: ..\firestore-client

dev_dependencies:
  test: ^1.16.0

flutter:
  fonts:
    - family: LibreBarcode39Text-Regular
      fonts:
        - asset: fonts/LibreBarcode39Text-Regular.ttf
    - family: JetBrainsMono-Regular
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
    - family: Audiowide-Regular
      fonts:
        - asset: fonts/Audiowide-Regular.ttf
    - family: VT323-Regular
      fonts:
        - asset: fonts/VT323-Regular.ttf
  assets:
    - images/
    - images/sprites/
    - images/website/
    - images/characters/
    - sprites/isometric/flame/
    - sprites/isometric/kid/arms_left/regular/
    - sprites/isometric/kid/arms_right/regular/
    - sprites/isometric/kid/body_male/shirt_blue/
    - sprites/isometric/kid/body_male/leather_armour/
    - sprites/isometric/kid/body_female/shirt_blue/
    - sprites/isometric/kid/body_female/leather_armour/
    - sprites/isometric/kid/body_arms/shirt_blue/
    - sprites/isometric/kid/hair_back/01/
    - sprites/isometric/kid/hair_front/01/
    - sprites/isometric/kid/hair_top/01/
    - sprites/isometric/kid/hands_left/gauntlets/
    - sprites/isometric/kid/hands_right/gauntlets/
    - sprites/isometric/kid/head/boy/
    - sprites/isometric/kid/head/girl/
    - sprites/isometric/kid/helms/steel/
    - sprites/isometric/kid/helms/wizard_hat/
    - sprites/isometric/kid/legs/leather/
    - sprites/isometric/kid/shadow/regular/
    - sprites/isometric/kid/torso/female/
    - sprites/isometric/kid/torso/male/
    - sprites/isometric/kid/weapons/bow/
    - sprites/isometric/kid/weapons/staff/
    - sprites/isometric/kid/weapons/sword/
    - sprites/isometric/kid/shoes_left/iron_plates/
    - sprites/isometric/kid/shoes_left/leather_boots/
    - sprites/isometric/kid/shoes_right/iron_plates/
    - sprites/isometric/kid/shoes_right/leather_boots/
    - sprites/front/kid/arms_left/regular/
    - sprites/front/kid/arms_right/regular/
    - sprites/front/kid/body_male/shirt_blue/
    - sprites/front/kid/body_male/leather_armour/
    - sprites/front/kid/body_female/leather_armour/
    - sprites/front/kid/body_arms/shirt_blue/
    - sprites/front/kid/hair_back/01/
    - sprites/front/kid/hair_front/01/
    - sprites/front/kid/hair_top/01/
    - sprites/front/kid/hands_left/gauntlets/
    - sprites/front/kid/hands_right/gauntlets/
    - sprites/front/kid/head/boy/
    - sprites/front/kid/head/girl/
    - sprites/front/kid/helms/steel/
    - sprites/front/kid/helms/wizard_hat/
    - sprites/front/kid/legs/leather/
    - sprites/front/kid/torso/female/
    - sprites/front/kid/torso/male/
    - sprites/front/kid/weapons/bow/
    - sprites/front/kid/weapons/staff/
    - sprites/front/kid/weapons/sword/
    - sprites/front/kid/shoes_left/iron_plates/
    - sprites/front/kid/shoes_left/leather_boots/
    - sprites/front/kid/shoes_right/iron_plates/
    - sprites/front/kid/shoes_right/leather_boots/
    - sprites/isometric/fallen/
    - sprites/isometric/skeleton/
    - sprites/isometric/butterfly/
    - sprites/isometric/bat/
    - audio/
    - audio/music/
    - audio/sounds/
    - audio/voices/