name: gamestream_flutter
description: next gen cloud gaming

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  archive: ^3.3.6
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.0.1
  just_audio: ^0.9.28
  just_audio_windows: ^0.2.0
  universal_html: ^2.0.8
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  golden_ratio: 1.0.6
  http: ^0.13.4
  intl: ^0.17.0
  typedef: ^1.0.12
  url_launcher: ^6.1.10

  lemon_sprite:
    path: ..\lemon_sprite
  lemon_widgets:
    path: ..\lemon_widgets
  lemon_math:
    path: ..\dart-lemon-math
  lemon_byte:
    path: C:\Users\Jerome\github\dart-lemon-byte
  lemon_engine:
    path: ..\dart-lemon-engine
  gamestream_http_client:
    path: ..\gamestream_http_client

dev_dependencies:
  test: ^1.16.0

flutter:
  fonts:
    - family: VT323-Regular
      fonts:
        - asset: fonts/VT323-Regular.ttf
    - family: REBUFFED
      fonts:
        - asset: fonts/REBUFFED.TTF
  assets:
    - images/
    - images/sprites/
    - images/website/
    - images/characters/
    - sprites/isometric/flame/
    - sprites/isometric/kid/south/arms_left/regular/
    - sprites/isometric/kid/south/arms_right/regular/
    - sprites/isometric/kid/south/body_male/shirt_blue/
    - sprites/isometric/kid/south/body_male/leather_armour/
    - sprites/isometric/kid/south/body_female/shirt_blue/
    - sprites/isometric/kid/south/body_female/leather_armour/
    - sprites/isometric/kid/south/body_arms/shirt_blue/
    - sprites/isometric/kid/south/hair_front/01/
    - sprites/isometric/kid/south/hair_back/01/
    - sprites/isometric/kid/south/hair_top/01/
    - sprites/isometric/kid/south/hair_top/02/
    - sprites/isometric/kid/south/hands_left/gauntlets/
    - sprites/isometric/kid/south/hands_right/gauntlets/
    - sprites/isometric/kid/south/head/boy/
    - sprites/isometric/kid/south/head/girl/
    - sprites/isometric/kid/south/helms/steel/
    - sprites/isometric/kid/south/helms/wizard_hat/
    - sprites/isometric/kid/south/legs/leather/
    - sprites/isometric/kid/south/shadow/regular/
    - sprites/isometric/kid/south/torso_top/female/
    - sprites/isometric/kid/south/torso_top/male/
    - sprites/isometric/kid/south/torso_bottom/female/
    - sprites/isometric/kid/south/torso_bottom/male/
    - sprites/isometric/kid/south/weapons/bow/
    - sprites/isometric/kid/south/weapons/staff/
    - sprites/isometric/kid/south/weapons/sword/
    - sprites/isometric/kid/south/shoes_left/iron_plates/
    - sprites/isometric/kid/south/shoes_left/leather_boots/
    - sprites/isometric/kid/south/shoes_right/iron_plates/
    - sprites/isometric/kid/south/shoes_right/leather_boots/
    - sprites/isometric/kid/west/arms_left/regular/
    - sprites/isometric/kid/west/arms_right/regular/
    - sprites/isometric/kid/west/body_male/shirt_blue/
    - sprites/isometric/kid/west/body_male/leather_armour/
    - sprites/isometric/kid/west/body_female/shirt_blue/
    - sprites/isometric/kid/west/body_female/leather_armour/
    - sprites/isometric/kid/west/body_arms/shirt_blue/
    - sprites/isometric/kid/west/hair_front/01/
    - sprites/isometric/kid/west/hair_back/01/
    - sprites/isometric/kid/west/hair_top/01/
    - sprites/isometric/kid/west/hair_top/02/
    - sprites/isometric/kid/west/hands_left/gauntlets/
    - sprites/isometric/kid/west/hands_right/gauntlets/
    - sprites/isometric/kid/west/head/boy/
    - sprites/isometric/kid/west/head/girl/
    - sprites/isometric/kid/west/helms/steel/
    - sprites/isometric/kid/west/helms/wizard_hat/
    - sprites/isometric/kid/west/legs/leather/
    - sprites/isometric/kid/west/shadow/regular/
    - sprites/isometric/kid/west/torso_top/female/
    - sprites/isometric/kid/west/torso_top/male/
    - sprites/isometric/kid/west/torso_bottom/female/
    - sprites/isometric/kid/west/torso_bottom/male/
    - sprites/isometric/kid/west/weapons/bow/
    - sprites/isometric/kid/west/weapons/staff/
    - sprites/isometric/kid/west/weapons/sword/
    - sprites/isometric/kid/west/shoes_left/iron_plates/
    - sprites/isometric/kid/west/shoes_left/leather_boots/
    - sprites/isometric/kid/west/shoes_right/iron_plates/
    - sprites/isometric/kid/west/shoes_right/leather_boots/  
    - sprites/isometric/crystal/
    - sprites/front/kid/arms_left/regular/
    - sprites/front/kid/arms_right/regular/
    - sprites/front/kid/body_male/shirt_blue/
    - sprites/front/kid/body_male/leather_armour/
    - sprites/front/kid/body_female/leather_armour/
    - sprites/front/kid/body_arms/shirt_blue/
    - sprites/front/kid/hair_back/01/
    - sprites/front/kid/hair_front/01/
    - sprites/front/kid/hair_top/01/
    - sprites/front/kid/hair_back/02/
    - sprites/front/kid/hair_front/02/
    - sprites/front/kid/hair_top/02/
    - sprites/front/kid/hands_left/gauntlets/
    - sprites/front/kid/hands_right/gauntlets/
    - sprites/front/kid/head/boy/
    - sprites/front/kid/head/girl/
    - sprites/front/kid/helms/steel/
    - sprites/front/kid/helms/wizard_hat/
    - sprites/front/kid/legs/leather/
    - sprites/front/kid/torso/female/
    - sprites/front/kid/torso/male/
    - sprites/front/kid/weapons/bow/
    - sprites/front/kid/weapons/staff/
    - sprites/front/kid/weapons/sword/
    - sprites/front/kid/shoes_left/iron_plates/
    - sprites/front/kid/shoes_left/leather_boots/
    - sprites/front/kid/shoes_right/iron_plates/
    - sprites/front/kid/shoes_right/leather_boots/
    - sprites/isometric/fallen/dead/
    - sprites/isometric/fallen/hurt/
    - sprites/isometric/fallen/idle/
    - sprites/isometric/fallen/running/
    - sprites/isometric/fallen/strike/
    - sprites/isometric/skeleton/south/
    - sprites/isometric/skeleton/west/
    - sprites/isometric/skeleton/shadow/
    - sprites/isometric/butterfly/
    - sprites/isometric/bat/
    - audio/
    - audio/ui/
    - audio/music/
    - audio/sounds/
    - audio/voices/