final clientRequestIndexUpdate = ClientRequest.Update.index;

enum ClientRequest {
  Update,
  Join,
  Join_Custom,
  Update_Cube3D,
  Attack,
  Revive,
  Equip,
  Ping,
  Purchase,
  SetCompilePaths,
  Version,
  Interact,
  Speak,
  SkipHour,
  ReverseHour,
  Teleport,
  AcquireAbility,
  SelectCharacterType,
  PerformAbility,
  SelectAbility,
  DeselectAbility,
  Upgrade_Ability,
  Reset_Character_Type,
  Leave_Lobby,
  Modify_Game,
  Sell_Slot,
  Equip_Slot,
  Unequip_Slot,
  Character_Save,
  Character_Load,
  Construct,
}

const clientRequests = ClientRequest.values;