enum ClientRequest {
  Join, // Open World
  Update,
  Revive,
  Equip,
  Ping,
  Purchase,
  SetCompilePaths,
  Version,
  Interact,
  Speak,
  SkipHour,
  ReverseHour,
  Teleport,
  CasteFireball,
  AcquireAbility,
  SelectCharacterType,
  PerformPrimaryAttack,
  PerformAbility,
  SelectAbility,
  DeselectAbility,
  Upgrade_Ability,
  Reset_Character_Type,
  Join_Moba,
  Join_Defense,
  Leave_Lobby,
}
