name: sync_renders
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  lemon_atlas:
    path: ../lemon_atlas

dev_dependencies:
  lints: ^2.0.0
