enum WebsiteDialog {
  Custom_Maps,
  Games,
  Subscription_Required,
  Invalid_Arguments,
  Confirm_Logout,
  Login,
  Account,
  Subscription_Successful,
  Subscription_Status_Changed,
  Account_Created,
  Welcome_2,
  Change_Public_Name,
  Change_Region,
  Login_Error,
  Confirm_Cancel_Subscription,
  Subscription_Cancelled,
}
