name: amulet_flutter
description: next gen cloud gaming

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/loading-icon.png"
#    icon_size: 48 # min:48, max:256, default: 48

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.2.1
  window_manager: ^0.3.7
  provider: ^6.0.5
  archive: ^3.3.6
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.0.1
  universal_html: ^2.0.8
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  golden_ratio: 1.0.6
  http: ^1.1.2
  intl: ^0.17.0
  url_launcher: ^6.1.10

  amulet_engine:
    path: ..\amulet_engine
  lemon_sprite:
    path: ..\lemon_sprite
  lemon_widgets:
    path: ..\tools\lemon_widgets
  lemon_engine:
    path: ..\tools\lemon_engine
  lemon_byte:
    path: ..\tools\lemon_byte
  gamestream_http_client:
    path: ..\gamestream_http_client

flutter:
  fonts:
    - family: VT323-Regular
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
  assets:
    - assets/fonts/
    - assets/audio/
    - assets/audio/ui/
    - assets/audio/music/
    - assets/audio/sounds/
    - assets/images/
    - assets/scenes/
    - assets/sprites/
    - assets/sprites/isometric/
    - assets/sprites/isometric/gameobjects/
    - assets/sprites/isometric/flame/
    - assets/sprites/isometric/wolf/flat/
    - assets/sprites/isometric/wolf/shadow/
    - assets/sprites/isometric/wolf/south/
    - assets/sprites/isometric/wolf/west/
    - assets/sprites/isometric/fallen/flat/
    - assets/sprites/isometric/fallen/shadow/
    - assets/sprites/isometric/fallen/south/
    - assets/sprites/isometric/fallen/west/
    - assets/sprites/isometric/skeleton/flat/
    - assets/sprites/isometric/skeleton/shadow/
    - assets/sprites/isometric/skeleton/south/
    - assets/sprites/isometric/skeleton/west/
    - assets/sprites/isometric/butterfly/
    - assets/sprites/isometric/moth/
    - assets/sprites/isometric/bat/
    - assets/sprites/isometric/crystal/
    - assets/sprites/isometric/kid/
    - assets/sprites/isometric/kid/diffuse/
    - assets/sprites/isometric/kid/diffuse/torso/
    - assets/sprites/isometric/kid/shadow/
    - assets/sprites/isometric/kid/south/
    - assets/sprites/isometric/kid/west/
    - assets/sprites/isometric/kid/south/hair/01/
    - assets/sprites/isometric/kid/south/hair/02/
    - assets/sprites/isometric/kid/south/hair/03/
    - assets/sprites/isometric/kid/south/head/boy/
    - assets/sprites/isometric/kid/south/head/girl/
    - assets/sprites/isometric/kid/south/torso/female/
    - assets/sprites/isometric/kid/south/torso/male/
    - assets/sprites/isometric/kid/south/weapons/bow/
    - assets/sprites/isometric/kid/south/weapons/staff/
    - assets/sprites/isometric/kid/south/shoes/leather_boots/
    - assets/sprites/isometric/kid/west/hair/01/
    - assets/sprites/isometric/kid/west/hair/02/
    - assets/sprites/isometric/kid/west/hair/03/
    - assets/sprites/isometric/kid/west/head/boy/
    - assets/sprites/isometric/kid/west/head/girl/
    - assets/sprites/isometric/kid/west/torso/female/
    - assets/sprites/isometric/kid/west/torso/male/
    - assets/sprites/isometric/kid/west/weapons/bow/
    - assets/sprites/isometric/kid/west/weapons/staff/
    - assets/sprites/isometric/kid/west/shoes/leather_boots/
    - assets/sprites/isometric/kid/diffuse/hair/01/
    - assets/sprites/isometric/kid/diffuse/hair/02/
    - assets/sprites/isometric/kid/diffuse/hair/03/
    - assets/sprites/isometric/kid/diffuse/head/boy/
    - assets/sprites/isometric/kid/diffuse/head/girl/
    - assets/sprites/isometric/kid/diffuse/shoes/leather_boots/
    - assets/sprites/isometric/kid/diffuse/torso/female/
    - assets/sprites/isometric/kid/diffuse/torso/male/
    - assets/sprites/isometric/kid/diffuse/weapons/bow/
    - assets/sprites/isometric/kid/diffuse/weapons/staff/
    - assets/sprites/front/kid/diffuse/body_female/leather_armour/
    - assets/sprites/front/kid/diffuse/body_female/shirt_blue/
    - assets/sprites/front/kid/diffuse/body_male/leather_armour/
    - assets/sprites/front/kid/diffuse/body_male/shirt_blue/
    - assets/sprites/front/kid/diffuse/hair/01/
    - assets/sprites/front/kid/diffuse/hair/02/
    - assets/sprites/front/kid/diffuse/hair/03/
    - assets/sprites/front/kid/diffuse/hair/04/
    - assets/sprites/front/kid/diffuse/hair/04/
    - assets/sprites/front/kid/diffuse/hands_left/gauntlets/
    - assets/sprites/front/kid/diffuse/hands_right/gauntlets/
    - assets/sprites/front/kid/diffuse/head/boy/
    - assets/sprites/front/kid/diffuse/head/girl/
    - assets/sprites/front/kid/diffuse/helms/steel/
    - assets/sprites/front/kid/diffuse/helms/wizard_hat/
    - assets/sprites/front/kid/diffuse/legs/leather/
    - assets/sprites/front/kid/diffuse/shoes/iron_plates/
    - assets/sprites/front/kid/diffuse/shoes/leather_boots/
    - assets/sprites/front/kid/diffuse/torso/female/
    - assets/sprites/front/kid/diffuse/torso/male/
    - assets/sprites/front/kid/diffuse/weapons/bow/
    - assets/sprites/front/kid/diffuse/weapons/staff/
    - assets/sprites/front/kid/diffuse/weapons/sword/
    - assets/sprites/isometric/zombie/
    - assets/sprites/isometric/zombie/flat/
    - assets/sprites/isometric/zombie/shadow/
    - assets/sprites/isometric/zombie/south/
    - assets/sprites/isometric/zombie/west/
    - assets/sprites/isometric/fallen_armoured/
    - assets/sprites/isometric/fallen_armoured/flat/
    - assets/sprites/isometric/fallen_armoured/shadow/
    - assets/sprites/isometric/fallen_armoured/south/
    - assets/sprites/isometric/fallen_armoured/west/
    - assets/sprites/isometric/kid/diffuse/weapons/broadsword/
    - assets/sprites/isometric/kid/south/weapons/broadsword/
    - assets/sprites/isometric/kid/west/weapons/broadsword/
    - assets/sprites/isometric/kid/diffuse/weapons/shortsword/
    - assets/sprites/isometric/kid/diffuse/weapons/sword_heavy_sapphire/
    - assets/sprites/isometric/kid/south/weapons/sword_heavy_sapphire/
    - assets/sprites/isometric/kid/west/weapons/sword_heavy_sapphire/
    - assets/sprites/isometric/gargoyle/
    - assets/sprites/isometric/gargoyle/flat/
    - assets/sprites/isometric/gargoyle/south/
    - assets/sprites/isometric/gargoyle/west/
    - assets/sprites/isometric/gargoyle/shadow/
    - assets/sprites/isometric/toad_warrior/
    - assets/sprites/isometric/toad_warrior/flat/
    - assets/sprites/isometric/toad_warrior/south/
    - assets/sprites/isometric/toad_warrior/west/
    - assets/sprites/isometric/kid/diffuse/armor/
    - assets/sprites/isometric/kid/south/armor/
    - assets/sprites/isometric/kid/west/armor/
    - assets/sprites/isometric/kid/diffuse/armor/tunic/
    - assets/sprites/isometric/kid/south/armor/tunic/
    - assets/sprites/isometric/kid/west/armor/tunic/
    - assets/sprites/isometric/kid/diffuse/helms/pointed_hat_black/
    - assets/sprites/isometric/kid/diffuse/helms/pointed_hat_purple/
    - assets/sprites/isometric/kid/south/helms/pointed_hat_black/
    - assets/sprites/isometric/kid/south/helms/pointed_hat_purple/
    - assets/sprites/isometric/kid/west/helms/pointed_hat_black/
    - assets/sprites/isometric/kid/west/helms/pointed_hat_purple/
    - assets/sprites/isometric/kid/diffuse/helms/steel_cap/
    - assets/sprites/isometric/kid/south/helms/steel_cap/
    - assets/sprites/isometric/kid/west/helms/steel_cap/
    - assets/sprites/isometric/kid/diffuse/armor/leather/
    - assets/sprites/isometric/kid/south/armor/leather/
    - assets/sprites/isometric/kid/west/armor/leather/
    - assets/sprites/isometric/kid/diffuse/armor/chainmail/
    - assets/sprites/isometric/kid/south/armor/chainmail/
    - assets/sprites/isometric/kid/west/armor/chainmail/
    - assets/sprites/isometric/kid/diffuse/armor/platemail/
    - assets/sprites/isometric/kid/south/armor/platemail/
    - assets/sprites/isometric/kid/west/armor/platemail/
    - assets/sprites/isometric/kid/diffuse/armor/robes/
    - assets/sprites/isometric/kid/south/armor/robes/
    - assets/sprites/isometric/kid/west/armor/robes/
    - assets/sprites/isometric/kid/diffuse/armor/cloak/
    - assets/sprites/isometric/kid/south/armor/cloak/
    - assets/sprites/isometric/kid/west/armor/cloak/
    - assets/sprites/isometric/kid/diffuse/helms/leather_cap/
    - assets/sprites/isometric/kid/south/helms/leather_cap/
    - assets/sprites/isometric/kid/west/helms/leather_cap/
    - assets/sprites/isometric/kid/diffuse/helms/feather_cap/
    - assets/sprites/isometric/kid/south/helms/feather_cap/
    - assets/sprites/isometric/kid/west/helms/feather_cap/
    - assets/sprites/isometric/kid/diffuse/shoes/grieves/
    - assets/sprites/isometric/kid/south/shoes/grieves/
    - assets/sprites/isometric/kid/west/shoes/grieves/
    - assets/sprites/isometric/kid/diffuse/shoes/black_slippers/
    - assets/sprites/isometric/kid/south/shoes/black_slippers/
    - assets/sprites/isometric/kid/west/shoes/black_slippers/
    - assets/sprites/isometric/kid/diffuse/shoes/treads/
    - assets/sprites/isometric/kid/south/shoes/treads/
    - assets/sprites/isometric/kid/west/shoes/treads/
    - assets/sprites/isometric/kid/diffuse/helms/full_helm/
    - assets/sprites/isometric/kid/south/helms/full_helm/
    - assets/sprites/isometric/kid/west/helms/full_helm/
    - assets/sprites/isometric/goblin/
    - assets/sprites/isometric/goblin/flat/
    - assets/sprites/isometric/goblin/south/
    - assets/sprites/isometric/goblin/west/
    - assets/sprites/isometric/goblin/shadow/
