name: amulet_engine
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fast_noise: ^1.0.1
  archive: ^3.4.9
  uuid: ^4.1.0

  lemon_bit:
    path: ..\tools\lemon_bit
  lemon_byte:
    path: ..\tools\lemon_byte
  lemon_math:
    path: ..\tools\lemon_math
  lemon_json:
    path: ..\tools\lemon_json
  lemon_lang:
    path: ..\tools\lemon_lang

