name: gamestream_ws
description: a websocket server for gamestream
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  lemon_byte: ^1.0.47
  web_socket_channel: ^2.3.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  http: ^0.13.5
  typedef: ^1.0.13
  fast_noise: ^1.0.1
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  uuid: ^4.1.0

dev_dependencies:
  test: ^1.16.0