
enum MMORequest {
  End_Interaction,
  Select_Weapon,
  Select_Item,
  Select_Treasure,
  Unequip_Head,
  Unequip_Body,
  Unequip_Legs,
  Drop_Equipped_Head,
  Drop_Equipped_Body,
  Drop_Equipped_Legs,
  Drop_Item,
  Drop_Weapon,
  Drop_Treasure,
  Select_Talk_Option,
  Toggle_Skills_Dialog,
  Toggle_Inventory_Open,
  Upgrade_Talent,
}