
enum NetworkRequestIsometric {
   Teleport,
   Revive,
   Weather_Set_Rain,
   Weather_Set_Wind,
   Weather_Set_Lightning,
   Weather_Toggle_Breeze,
   Time_Set_Hour,
   Editor_Load_Game,
   Move_Selected_Collider_To_Mouse,
   Debug_Character_Walk_To_Mouse,
   Debug_Character_Toggle_Auto_Attack_Nearby_Enemies,
   Debug_Character_Toggle_Path_Finding_Enabled,
   Debug_Character_Toggle_Run_To_Destination,
   Debug_Character_Debug_Update,
   Debug_Character_Set_Character_Type,
   Debug_Character_Set_Weapon_Type,
   Debug_Select,
   Debug_Command,
   Debug_Attack,
   Select_GameObject,
   Toggle_Debugging,
   Toggle_Controls_Can_Target_Enemies,
   Set_Seconds_Per_Frame,
}