
enum MMOSkill {
  Add_Slot_Weapon_1,
  Add_Slot_Weapon_2,
  Add_Slot_Weapon_3,
  Add_Treasure_Slot_1,
  Add_Treasure_Slot_2,
  Add_Treasure_Slot_3,
  Max_Health_1,
  Max_Health_2,
  Max_Health_3,
  Max_Magic_1,
  Max_Magic_2,
  Max_Magic_3,
  Sword_Mastery_1,
  Sword_Mastery_2,
  Sword_Mastery_3,
  Bow_Mastery_1,
  Bow_Mastery_2,
  Bow_Mastery_3,
  Movement_speed_1,
  Movement_speed_2,
  Max_Potions_1,
  Max_Potions_2,
  Max_Potions_3,
}