name: bleed_client
description: A client for gamestream platform

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^5.2.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  url_strategy: ^0.2.0
  lemon_watch: ^1.0.4
  lemon_math: ^1.1.5
  lemon_engine: ^0.2.86
  audioplayers: ^0.19.1
  universal_html: ^2.0.8
  positioned_tap_detector: ^1.0.3
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  clipboard: ^0.1.3
  animated_text_kit: ^4.2.1
  shared_preferences: ^2.0.11

flutter:
  fonts:
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf
    - family: LuckiestGuy-Regular
      fonts:
        - asset: fonts/LuckiestGuy-Regular.ttf
  assets:
     - images/
     - audio/
     - assets/
     - images/icons/