name: bleed_client
description: A client for the game BLEED

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lemon_watch: ^1.0.1
  lemon_math: ^1.1.4
  lemon_engine: ^0.1.1
  audioplayers: ^0.19.1
  universal_html: ^2.0.8
  positioned_tap_detector: ^1.0.3
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  clipboard: ^0.1.3
  neuro: ^0.3.1
  animated_text_kit: ^4.2.1
  shared_preferences: ^2.0.7

flutter:
  fonts:
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
  uses-material-design: true
  assets:
     - images/
     - audio/
