name: lemon_widgets
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter


  universal_html: ^2.0.8


