
name: amulet_client
description: gothic hack and slash rpg

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.2.1
  archive: ^3.3.6
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.0.1
  golden_ratio: 1.0.6
  lemon_watch: ^1.1.2

  amulet_common:
    path: ..\amulet_common
  lemon_sprite:
    path: ..\tools\lemon_sprite
  lemon_widgets:
    path: ..\tools\lemon_widgets
  lemon_engine:
    path: ..\tools\lemon_engine
  lemon_byte:
    path: ..\tools\lemon_byte
  lemon_math:
    path: ..\tools\lemon_math
  lemon_bit:
     path: ..\tools\lemon_bit
  gamestream_http_client:
    path: ..\gamestream_http_client
  lemon_json:
    path: ..\tools\lemon_json
  lemon_io:
    path: ..\tools\lemon_io
  lemon_lang:
    path: ..\tools\lemon_lang

