enum ClientRequest{
  Game_Join_Open_World,
  Game_Join_Random,
  Lobby_Create,
  Lobby_Join,
  Lobby_Exit,
  Lobby_Update,
  Game_Join,
  Game_Update,
  Player_Revive,
  Player_Equip,
  Spawn_Npc,
  Player_Throw_Grenade,
  Player_Use_MedKit,
  Ping,
  Game_Join_Fortress,
}