name: amulet_common
description: a shared library between the client and server
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  lemon_math:
    path: ..\tools\lemon_math
  lemon_lang:
    path: ..\tools\lemon_lang

dev_dependencies:
  lints: ^2.1.0

