name: gamestream_firestore
description: A restful server for accessing the firestore database
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  shelf: ^1.4.1
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  http: ^0.13.4
  typedef: ^1.0.5

