name: gamestream_firestore
description: A library for accessing gamestream's firestore
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  shelf: ^1.2.0
  googleapis: ^7.0.0
  googleapis_auth: ^1.1.0

