
enum GameError {
  CharacterTypeAlreadySelected,
  GameNotFound,
  PlayerNotFound,
  ClientRequestRequired,
  UnrecognizedClientRequest,
  InvalidPlayerUUID,
  ClientRequestArgumentsEmpty,
  PlayerStillAlive,
  PlayerDead,
  InvalidArguments,
  LobbyNotFound,
  LobbyUserNotFound,
  GameFull,
  CannotRevive,
  CannotSpawnNpc,
  InvalidPurchaseType,
  IntegerExpected,
  InsufficientFunds,
  WeaponNotAcquired,
  WeaponAlreadyAcquired,
  InsufficientSkillPoints,
  SkillLocked,
}