name: gamestream_users
description: A restful server for gamestream
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  shelf: ^1.2.0
  googleapis: ^7.0.0
  googleapis_auth: ^1.1.0
  stripe: ^4.5.0
  http: ^0.13.4

