// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0IMHmkcbe3HoNzU0e172ccRUQA3nUrSg',
    appId: '1:770338460266:web:5627a8c7ac285e10807013',
    messagingSenderId: '770338460266',
    projectId: 'lemon-sprites',
    authDomain: 'lemon-sprites.firebaseapp.com',
    storageBucket: 'lemon-sprites.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65DUC9BNUH2Yesb1eJHdZO5DzhGTOW94',
    appId: '1:770338460266:android:2019084673582aa1807013',
    messagingSenderId: '770338460266',
    projectId: 'lemon-sprites',
    storageBucket: 'lemon-sprites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACBDNCPb4sR5woVmogWLRone9dbcgDM4Q',
    appId: '1:770338460266:ios:0c2e2c7641e0240b807013',
    messagingSenderId: '770338460266',
    projectId: 'lemon-sprites',
    storageBucket: 'lemon-sprites.appspot.com',
    iosClientId: '770338460266-ba2s6gudeugtn5r2p1hcqulp7r09kf0m.apps.googleusercontent.com',
    iosBundleId: 'com.lemon.lemonSprites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACBDNCPb4sR5woVmogWLRone9dbcgDM4Q',
    appId: '1:770338460266:ios:6e13605282839840807013',
    messagingSenderId: '770338460266',
    projectId: 'lemon-sprites',
    storageBucket: 'lemon-sprites.appspot.com',
    iosClientId: '770338460266-l0rb4j179hk4vun2i7hrji482fm485aq.apps.googleusercontent.com',
    iosBundleId: 'com.lemon.lemonSprites.RunnerTests',
  );
}
