const double cameraSpeed = 2;
const double cameraFollow = 0.02;
const int fps = 30;
const int milliSecondsPerSecond = 1000;
const int smoothingFrames = 3;
const String localhost = "ws://localhost:8080";
const gpcUrl = 'https://bleed-31-osbmaezptq-ey.a.run.app';
String gpc = gpcUrl.replaceAll("https", "wss") + "/:8080";
String host = localhost;