name: gamestream_server
description: The Websocket server for gamestream
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  algorithmic: ^0.0.11
  lemon_byte: ^1.0.42
  web_socket_channel: ^2.3.0
  shelf_web_socket: ^1.0.1
  shelf_router: ^1.1.2
  uuid: ^3.0.4
  http: ^0.13.5
  typedef: ^1.0.8
  fast_noise: ^1.0.1
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0

dev_dependencies:
  test: ^1.16.0