name: isometric_engine
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  lemon_byte: ^1.0.47
  fast_noise: ^1.0.1
  typedef: ^1.0.13

dev_dependencies:
  lints: ^2.0.0
