name: isometric_engine
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fast_noise: ^1.0.1
  archive: ^3.4.9

dev_dependencies:
  lints: ^2.0.0
