
enum NetworkRequestAmulet {
  End_Interaction,
  Select_Talk_Option,
  Spawn_Random_Enemy,
  Acquire_Amulet_Item,
  Player_Change_Game,
  Skip_Tutorial,
  Reset,
  Drop_Item_Type,
  Select_Skill_Type_Left,
  Select_Skill_Type_Right,
  Refill_Player_Health_Magic,
  Toggle_Debug_Enabled,
  Toggle_Skill_Type,
  Spawn_Random_Amulet_Item,
  Spawn_Amulet_Item,
  Pickup_Amulet_Item,
  Sell_Amulet_Item,
  Upgrade_Slot_Type,
  Cheat_Acquire_Gold,
  Use_Potion_Health,
  Use_Potion_Magic,
  End_Upgrade_Mode,
  Stash_Sell,
}