import 'package:gamestream_flutter/enums/icon_type.dart';

class AtlasIcons {

  static const Size = 32.0;

  static double getSrcX(int itemType) => const <int, double> {
    IconType.Checkbox_True: 304,
    IconType.Checkbox_False: 176,
    IconType.Zoom: Size * 1,
    IconType.Home: 138,
    IconType.Cog: 138,
    IconType.Cog_Turned: 303,
    IconType.Fullscreen: Size * 3,
    IconType.Slot: Size * 1,
    IconType.Rain_None: 128,
    IconType.Rain_Light: 128,
    IconType.Rain_Heavy: 128,
    IconType.Lightning_Off: 128,
    IconType.Lightning_Nearby: 128,
    IconType.Lightning_On: 128,
    IconType.Wind_Calm: 128,
    IconType.Wind_Gentle: 128,
    IconType.Wind_Strong: 128,
    IconType.Inventory: 64,
    IconType.Sound_Enabled: 1,
    IconType.Sound_Disabled: 1,
    IconType.Plus: 32,
    IconType.Minus: 64,
    IconType.Heart: 193,
    IconType.Damage: 48,
    IconType.Energy: 193,
    IconType.Primary_Weapon: 208,
    IconType.Secondary_Weapon: 240,
    IconType.Tertiary_Weapon: 240,
    IconType.Head_Type: 262,
    IconType.Body_Type: 292,
    IconType.Leg_Type: 214,
    IconType.Bag_White: 245,
    IconType.Power_None: 0,
    IconType.Power_Bomb: 495,
    IconType.Power_Shield: 468,
    IconType.Power_Invisible: 465,
    IconType.Power_Teleport: 503,
    IconType.Power_Revive: 466,
    IconType.Power_Stun: 674,
    IconType.Music_Enabled: 1,
    IconType.Music_Disabled: 1,
  }[itemType] ?? 0;

  static double getSrcY(int itemType) => const  <int, double> {
    IconType.Checkbox_True: 704,
    IconType.Checkbox_False: 704,
    IconType.Arrows_Up: Size * 0,
    IconType.Arrows_Down: Size * 1,
    IconType.Arrows_North: Size * 2,
    IconType.Arrows_East: Size * 3,
    IconType.Arrows_South: Size * 4,
    IconType.Arrows_West: Size * 5,
    IconType.Home: 515,
    IconType.Cog: 515,
    IconType.Cog_Turned: 515,
    IconType.Sound_Enabled: 736,
    IconType.Sound_Disabled: 872,
    IconType.Fullscreen: 0,
    IconType.Zoom: 0,
    IconType.Slot: Size * 1,
    IconType.Rain_None: 64 * 0,
    IconType.Rain_Light: 64 * 1,
    IconType.Rain_Heavy: 64 * 2,
    IconType.Lightning_Off: 64 * 0,
    IconType.Lightning_Nearby: 64 * 3,
    IconType.Lightning_On: 64 * 4,
    IconType.Wind_Calm: 64 * 0,
    IconType.Wind_Gentle: 64 * 5,
    IconType.Wind_Strong: 64 * 6,
    IconType.Inventory: 32,
    IconType.Plus: 96,
    IconType.Minus: 96,
    IconType.Heart: 209,
    IconType.Damage: 448,
    IconType.Energy: 295,
    IconType.Primary_Weapon: 145,
    IconType.Secondary_Weapon: 147,
    IconType.Tertiary_Weapon: 166,
    IconType.Head_Type: 147,
    IconType.Body_Type: 147,
    IconType.Leg_Type: 163,
    IconType.Bag_White: 179,
    IconType.Power_None: 0,
    IconType.Power_Bomb: 1,
    IconType.Power_Shield: 115,
    IconType.Power_Invisible: 177,
    IconType.Power_Teleport: 115,
    IconType.Power_Revive: 84,
    IconType.Power_Stun: 113,
    IconType.Music_Enabled: 499,
    IconType.Music_Disabled: 609,
  }[itemType] ?? 0;

  static double getSrcWidth(int itemType) => const  <int, double> {
    IconType.Checkbox_True: 112,
    IconType.Checkbox_False: 112,
    IconType.Home: 155,
    IconType.Cog: 155,
    IconType.Cog_Turned: 155,
    IconType.Sound_Enabled: 137,
    IconType.Sound_Disabled: 137,
    IconType.Primary_Weapon: 31,
    IconType.Secondary_Weapon: 12,
    IconType.Tertiary_Weapon: 16,
    IconType.Head_Type: 20,
    IconType.Body_Type: 26,
    IconType.Leg_Type: 21,
    IconType.Bag_White: 23,
    IconType.Heart: 94,
    IconType.Energy: 75,
    IconType.Power_None: 0,
    IconType.Power_Bomb: 38,
    IconType.Power_Shield: 24,
    IconType.Power_Invisible: 65,
    IconType.Power_Teleport: 18,
    IconType.Power_Revive: 26,
    IconType.Power_Stun: 87,
    IconType.Music_Enabled: 90,
    IconType.Music_Disabled: 90,
  }[itemType] ?? getSrcSize(itemType);

  static double getSrcHeight(int itemType) => const  <int, double> {
    IconType.Checkbox_True: 112,
    IconType.Checkbox_False: 112,
    IconType.Home: 155,
    IconType.Cog: 155,
    IconType.Cog_Turned: 155,
    IconType.Sound_Enabled: 107,
    IconType.Sound_Disabled: 107,
    IconType.Primary_Weapon: 13,
    IconType.Secondary_Weapon: 10,
    IconType.Tertiary_Weapon: 5,
    IconType.Head_Type: 26,
    IconType.Body_Type: 26,
    IconType.Leg_Type: 26,
    IconType.Bag_White: 26,
    IconType.Heart: 85,
    IconType.Energy: 157,
    IconType.Power_None: 0,
    IconType.Power_Bomb: 45,
    IconType.Power_Shield: 25,
    IconType.Power_Invisible: 74,
    IconType.Power_Teleport: 25,
    IconType.Power_Revive: 26,
    IconType.Power_Stun: 174,
    IconType.Music_Enabled: 98,
    IconType.Music_Disabled: 98,
  }[itemType] ?? getSrcSize(itemType);

  static double getSrcSize(int itemType) => const  <int, double> {
    IconType.Heart: 48.0,
    IconType.Damage: 48.0,
    IconType.Energy: 48.0,
    IconType.Rain_None: 64.0,
    IconType.Rain_Light: 64.0,
    IconType.Rain_Heavy: 64.0,
    IconType.Lightning_Off: 64.0,
    IconType.Lightning_Nearby: 64.0,
    IconType.Lightning_On: 64.0,
    IconType.Wind_Calm: 64.0,
    IconType.Wind_Gentle: 64.0,
    IconType.Wind_Strong: 64.0,
  }[itemType] ?? 32;
}
